### ISSUE TITLE
gulp-util not found

### ISSUE THREAD

**Issue by sartaj** [sergiomasellis/gulp-testem#2]
```
$ gulp testem

module.js:340
    throw err;
          ^
Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/dev/app/node_modules/gulp-testem/index.js:5:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I installed gulp-testem using `npm install gulp-testem --save-dev`.

It seems as if `gulp-util` is a dev dependency for this project in the `package.json`, as thus it doesn't install when installed from NPM with `npm install gulp-testem`.

**Comment by ikari-pl** [comment]
I can confirm both this issue and the solution of manually installing the package.
